model:
  name: "BadDAE"
  load_ckpt: True
  w_init_min: 0.01
  w_init_max: 0.1

augmenter:
  seed: 108
  factor: 1
  do_vshift: false
  do_smear: false
  smear_radius: 3
  smear_filter: "max"
  do_noise: true
  noise_factor: 0.05
  overfit_num: 0
  overfit_index: 0
  overfit_multiplier: 3200

encoder:
  kernel_size: 3
  padding: 1
  stride: 1
  channel_size: 8
  pool_size: 2
  activation: "silu"

decoder:
  padding: 0
  stride: 2
  channel_size: 8
  out_dim2: 1
  activation: "silu"

device: "cuda:0"

trainer:
  log_dir: "ml/outputs/runs"
  loss: "mse"
  epochs: 10
  log_tag: "overfit_1"
  noise_factor: 0.0
  learning_rate: 0.001
  batch_size: 32

loader:
  batch_size: 32
  shuffle: true
  num_workers: 4