device: "cuda:0"

model:
  path: "bad_dae"
  name: "BadDAE"
  load_ckpt: False
  w_init_min: 0.01
  w_init_max: 0.1

augmenter:
  seed: 108
  factor: 1
  do_vshift: false
  do_smear: false
  smear_radius: 3
  smear_filter: "max"
  do_noise: true
  noise_factor: 0.05
  overfit_num: 10
  overfit_index: 0
  overfit_multiplier: 3200

trainer:
  log_dir: "ml/outputs/runs"
  loss: "mse"
  epochs: 10
  log_tag: "overfit_10"
  noise_factor: 0.0
  learning_rate: 0.01
  batch_size: 32

loader:
  batch_size: 32
  shuffle: true
  num_workers: 4